### ISSUE TITLE
Screenshots? 😺

### ISSUE THREAD

**Issue by eMPee584** [marketagaldova/logfeline#1]
… 😸

**Comment by marketagaldova** [comment]
Hey there, i did a thing! Feel free to give it a go with 0.2.0~ It's just an added `screenshot` command in the existing command system.

If im gonna be honest tho, i have next to no experience with images, color spaces, pixel formats and all that kinda stuff, so i convenientely ignored some parts of that. It seems to work fine on all of my devices tho, so hopefully it's not an issue.
